[package]
name = "rusty_shadowrun_creator"
version = "0.1.0"
authors = ["Alan Hietala <alan.hietala@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "0.6.2"
enum-iterator = "0.6.0"
